# Exported from Render on 2026-08-28T20:56:31Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: twin
      runtime: python
      repo: https://github.com/kasir-barati/kasir-barati.github.io
      plan: free
      envVars:
      - key: GRADIO_SERVER_PORT
        sync: false
      - key: GRADIO_SERVER_NAME
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: GMAIL_ADDRESS
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      region: frankfurt
      # 👇 The command to build your app before each deploy.
      buildCommand: rm -rf .venv && uv sync --frozen && uv cache prune --ci
      # 👇 The command to start your app with each deploy.
      startCommand: make start
      # 👇 Automatically deploy the service whenever you update its code or configuration.
      autoDeployTrigger: commit
      # 👇 Runs commands from this directory instead of the repository root, code changes outside of this directory do NOT trigger an auto-deploy. 
      rootDir: twin
